services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev

    container_name: tcc-app

    environment:
      SPRING_PROFILES_ACTIVE: dev

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_SECRET: ${JWT_SECRET:?Defina JWT_SECRET no arquivo .env}

      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      APP_PASSWORD_RESET_SQS_QUEUE_URL: ${APP_PASSWORD_RESET_SQS_QUEUE_URL}

    ports:
      - "8080:8080"
      - "5005:5005"

    volumes:
      - ./src:/app/src

    command:
      - ./mvnw
      - spring-boot:run
      - -Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
