# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-small-poetry-ac9pj9cg.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

# JPA dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Prod: show-sql desabilitado (sobrescreve o default)
spring.jpa.show-sql=false