-- V10: Tabela de fotos de execuções de procedimentos
-- Depende de: procedure_executions

CREATE TABLE procedure_photos (
    id                     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    procedure_execution_id BIGINT       NOT NULL,
    image_url              VARCHAR(500) NOT NULL,
    file_name              VARCHAR(255) NOT NULL,
    uploaded_at            TIMESTAMP    NOT NULL,

    CONSTRAINT fk_procedure_photos_execution FOREIGN KEY (procedure_execution_id) REFERENCES procedure_executions(id)
);
