-- V11: Tabela de importações de leituras de dispositivos
-- Depende de: patients, patient_devices

CREATE TABLE reading_imports (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id        BIGINT       NOT NULL,
    patient_device_id BIGINT       NOT NULL,
    source_file       VARCHAR(500) NOT NULL,
    imported_at       TIMESTAMP    NOT NULL,

    CONSTRAINT fk_reading_imports_patient FOREIGN KEY (patient_id)        REFERENCES patients(id),
    CONSTRAINT fk_reading_imports_device  FOREIGN KEY (patient_device_id) REFERENCES patient_devices(id)
);
