-- V12: Tabela de leituras de saúde (sinais vitais)
-- Depende de: patients, patient_devices, reading_imports

CREATE TABLE health_readings (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id        BIGINT       NOT NULL,
    patient_device_id BIGINT       NOT NULL,
    reading_import_id BIGINT,
    reading_type      VARCHAR(100) NOT NULL,
    value             VARCHAR(100) NOT NULL,
    unit              VARCHAR(50),
    measured_at       TIMESTAMP    NOT NULL,

    CONSTRAINT fk_health_readings_patient FOREIGN KEY (patient_id)        REFERENCES patients(id),
    CONSTRAINT fk_health_readings_device  FOREIGN KEY (patient_device_id) REFERENCES patient_devices(id),
    CONSTRAINT fk_health_readings_import  FOREIGN KEY (reading_import_id) REFERENCES reading_imports(id)
);
