-- V13: Tabela de alertas gerados por leituras anormais
-- Depende de: patients, health_readings

CREATE TABLE alerts (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id        BIGINT       NOT NULL,
    health_reading_id BIGINT,
    severity          VARCHAR(50)  NOT NULL,
    title             VARCHAR(255) NOT NULL,
    description       TEXT,
    status            VARCHAR(50)  NOT NULL,
    created_at        TIMESTAMP    NOT NULL,

    CONSTRAINT fk_alerts_patient       FOREIGN KEY (patient_id)        REFERENCES patients(id),
    CONSTRAINT fk_alerts_health_reading FOREIGN KEY (health_reading_id) REFERENCES health_readings(id)
);
