-- V2: Tabela de hospitais
-- Não depende de nenhuma outra tabela

CREATE TABLE hospitals (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    cnpj       VARCHAR(14)  NOT NULL UNIQUE,
    phone      VARCHAR(20),
    email      VARCHAR(255),
    address    VARCHAR(255),
    city       VARCHAR(100),
    state      VARCHAR(2),
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL
);
