-- V4: Tabela de pacientes
-- Depende de: users

CREATE TABLE patients (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL UNIQUE,
    full_name  VARCHAR(255) NOT NULL,
    cpf        VARCHAR(11)  NOT NULL UNIQUE,
    birth_date DATE         NOT NULL,
    gender     VARCHAR(20),
    phone      VARCHAR(20),
    weight     DOUBLE PRECISION,
    height     DOUBLE PRECISION,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,

    CONSTRAINT fk_patients_user FOREIGN KEY (user_id) REFERENCES users(id)
);
