-- V5: Tabela de associação doutor-paciente (N:N)
-- Depende de: doctors, patients

CREATE TABLE doctor_patients (
    id         BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id  BIGINT    NOT NULL,
    patient_id BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_doctor_patients_doctor  FOREIGN KEY (doctor_id)  REFERENCES doctors(id),
    CONSTRAINT fk_doctor_patients_patient FOREIGN KEY (patient_id) REFERENCES patients(id)
);
