-- V7: Tabela de procedimentos médicos (templates)
-- Depende de: doctors

CREATE TABLE procedures (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id          BIGINT       NOT NULL,
    title              VARCHAR(255) NOT NULL,
    description        TEXT,
    estimated_duration INT,
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP    NOT NULL,

    CONSTRAINT fk_procedures_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);
