-- V8: Tabela de procedimentos agendados para pacientes
-- Depende de: patients, procedures, doctors

CREATE TABLE patient_procedures (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id   BIGINT      NOT NULL,
    procedure_id BIGINT      NOT NULL,
    doctor_id    BIGINT      NOT NULL,
    start_date   DATE        NOT NULL,
    end_date     DATE,
    status       VARCHAR(50) NOT NULL,
    notes        TEXT,

    CONSTRAINT fk_patient_procedures_patient   FOREIGN KEY (patient_id)   REFERENCES patients(id),
    CONSTRAINT fk_patient_procedures_procedure FOREIGN KEY (procedure_id) REFERENCES procedures(id),
    CONSTRAINT fk_patient_procedures_doctor    FOREIGN KEY (doctor_id)    REFERENCES doctors(id)
);
